[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
log = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }
socket2 = { workspace = true }
raylib = { workspace = true }
