[workspace]
resolver = "3"
members = ["shared", "server", "client", "lobby"]

[workspace.dependencies]
log = { version = "0.4" }
env_logger = { version = "0.11" }
dotenvy = { version = "0.15" }
tokio = { version = "1.47", features = ["full"] }
tokio-util = { version = "0.7" }
socket2 = { version = "0.6" }
uuid = { version = "1.18" }
rand = { version = "0.9" }
futures = { version = "0.3" }
raylib = { version = "5.5" }
strum = { version = "0.27", features = ["derive"] }
secr = { version = "1.2" }

# todo: check usage in lobby
actix-web = { version = "4.11" }
sqlx = { version = "0.8", features = ["postgres", "macros", "uuid", "chrono", "runtime-tokio", "tls-native-tls"] }
serde = { version = "1.0" }
serde_json = { version = "1.0", features = ["preserve_order"] }
chrono = { version = "0.4", features = ["serde", "now"] }
reqwest = { version = "0.12", features = ["json", "native-tls-vendored", "multipart", "stream"] }
base64 = { version = "0.22" }
