[workspace]
resolver = "3"
members = ["shared", "server", "client", "lobby"]

[workspace.dependencies]
log = { version = "0.4" }
env_logger = { version = "0.11" }
dotenvy = { version = "0.15" }
tokio = { version = "1.47", features = ["full"] }
tokio-util = { version = "0.7" }
socket2 = { version = "0.6" }
uuid = { version = "1.18", features = ["serde", "v7"] }
rand = { version = "0.9" }
futures = { version = "0.3" }
raylib = { version = "5.5" }
strum = { version = "0.27", features = ["derive"] }
secr = { version = "1.2" }
actix-web = { version = "4.11" }
actix-ws = { version = "0.4" }
bytes = { version = "1" }
bytestring = { version = "1" }
sqlx = { version = "0.8", features = ["postgres", "macros", "uuid", "chrono", "runtime-tokio", "tls-native-tls"] }
base64 = { version = "0.22" }
bcrypt = { version = "0.17" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
rmp-serde = { version = "1.3" }
chrono = { version = "0.4", features = ["serde", "now"] }

# Not used yet
reqwest = { version = "0.13.2", features = ["json", "native-tls-vendored", "multipart", "stream"] }
