[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { workspace = true }
uuid = { workspace = true }
dotenvy = { workspace = true }
tokio = { workspace = true }
socket2 = { workspace = true }
log = { workspace = true }
