[package]
name = "lobby"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared", features = ["sqlx"] }

log = { workspace = true }
env_logger = { workspace = true }
actix-web = { workspace = true }
sqlx = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
bcrypt = { workspace = true }
rmp-serde = { workspace = true }
